[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'Shougo/denite.nvim'
depends = ['neomru.vim']

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/neocomplete.vim'
if   = '''! has('nvim')'''

[[plugins]]
repo = 'w0rp/ale'

[[plugins]]
repo = 'Shougo/vimfiler'
depends = 'vimproc'

[[plugins]]
repo = 'Shougo/defx.nvim'

[[plugins]]
repo = 'roxma/nvim-yarp'
if   = '''! has('nvim')'''

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'
if   = '''! has('nvim')'''

[[plugins]]
repo = 'Shougo/deol.nvim'

[[plugins]]
repo = 'kmnk/denite-dirmark'
depends = ['denite.nvim']

[[plugins]]
repo = 'Shougo/vimproc'
build = 'make -f make_mac.mak'

[[plugins]]
repo = 'Shougo/vimshell'
depends = 'vimproc'
if   = '''! has('nvim')'''

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'rking/ag.vim'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'

[[plugins]]
repo = 'prabirshrestha/vim-lsp'

[[plugins]]
repo = 'mattn/vim-lsp-settings'
depends = 'vim-lsp'

[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'
depends = 'asyncomplete.vim'

[[plugins]]
repo = 'mattn/sonictemplate-vim'

[[plugins]]
repo = 'editorconfig/editorconfig-vim.git'

[[plugins]]
repo = 'ntpeters/vim-better-whitespace'

[[plugins]]
repo = 'tomtom/tcomment_vim'

[[plugins]]
repo = 'ConradIrwin/vim-bracketed-paste'
