# [[plugins]]
# repo = 'tpope/vim-endwise'
# on_ft = ['ruby', 'vim', 'zsh']

## [[plugins]]
## repo = 'kana/vim-smartinput'
## on_ft = ['cs']

[[plugins]]
repo = 'tpope/vim-rails'
on_ft = ['ruby']

[[plugins]]
repo = 'vim-ruby/vim-ruby'
on_ft = ['ruby']

[[plugins]]
repo = 'slim-template/vim-slim'
on_ft = ['slim']

[[plugins]]
repo = 'tpope/vim-markdown'
on_ft = ['markdown']

## [[plugins]]
## repo = 'OmniSharp/omnisharp-vim'
## on_ft = ['cs']
## build = 'xbuild server/OmniSharp.sln' # on mac and linux
## on windows
## build = 'MSBuild.exe server/OmniSharp.sln /p:Platform="Any CPU"'

## [[plugins]]
## repo = 'OrangeT/vim-csharp'
## on_ft = ['cs']

## [[plugins]]
## repo = 'tpope/vim-dispatch'
## on_ft = ['cs']

[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = ['typescript']

[[plugins]]
repo = 'mhartington/nvim-typescript'
on_ft = ['typescript']

[[plugins]]
repo = 'ejholmes/vim-forcedotcom'
on_ft = ['st']
